// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eputpnoxzdjkmdbechwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwdXRwbm94emRqa21kYmVjaHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MzExMDQsImV4cCI6MjA2OTIwNzEwNH0.0JvJ5ggTF-uzPvUHzdWROmrzI8T--uEMXZQR0csEBIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);